# Turn debug on to display more information about exceptions, throw more
# exceptions early and more - but at the cost of security and performance.
# Turn on in development, turn off in production.
debug: false

# Configurators are classes that are resolved from the service container and ran
# when the application is booting.
configurators:
  - Autarky\Logging\DefaultLogConfigurator
  - Autarky\Routing\DefaultRouteConfigurator

# Class-based error handlers can be added here.
# Read more: https://github.com/autarky/framework/wiki/Error-Handling
error_handlers:
  - Autarky\Logging\LoggingErrorHandler
